export interface Prospect {
  id: string;
  name: string;
  origin: string;
  age: number;
  position: string;
  tier: string;
  rating: number;
  squat: number;
  bench: number;
  fortyDash?: string;
  yardsPerCarry?: string;
  tackleCompletion?: string;
  broncoTest?: string;
  goalKicking?: string;
  videoUrl?: string;
  recruitingStatus?: string;
  classYear?: string;
}

export const prospects: Prospect[] = [
  // --- PROPS ---
  {
    id: "carlton-banks",
    name: "Carlton Banks",
    origin: "USA",
    age: 22,
    position: "Prop",
    tier: "Tier 1 Elite",
    rating: 93,
    squat: 580,
    bench: 430,
    fortyDash: "4.92",
    yardsPerCarry: "5.5",
    tackleCompletion: "95%",
    broncoTest: "4:55",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2026",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "henry-vance",
    name: "Henry Vance",
    origin: "USA",
    age: 21,
    position: "Prop",
    tier: "Tier 1 Elite",
    rating: 91,
    squat: 565,
    bench: 415,
    fortyDash: "4.98",
    yardsPerCarry: "5.2",
    tackleCompletion: "94%",
    broncoTest: "5:02",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2027",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "viktor-petrov",
    name: "Viktor Petrov",
    origin: "Canada",
    age: 22,
    position: "Prop",
    tier: "Tier 2",
    rating: 88,
    squat: 550,
    bench: 400,
    fortyDash: "5.05",
    yardsPerCarry: "4.9",
    tackleCompletion: "92%",
    broncoTest: "5:10",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2027",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "braden-o-shea",
    name: "Braden O'Shea",
    origin: "Ireland / USA",
    age: 20,
    position: "Prop",
    tier: "Tier 2",
    rating: 86,
    squat: 540,
    bench: 390,
    fortyDash: "5.10",
    yardsPerCarry: "4.7",
    tackleCompletion: "91%",
    broncoTest: "5:15",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2028",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },

  // --- LOCKS ---
  {
    id: "jaxson-reed",
    name: "Jaxson Reed",
    origin: "USA",
    age: 20,
    position: "Lock",
    tier: "Tier 1 Elite",
    rating: 94,
    squat: 540,
    bench: 395,
    fortyDash: "4.78",
    yardsPerCarry: "6.4",
    tackleCompletion: "94%",
    broncoTest: "4:38",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2027",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "soren-jensen",
    name: "Soren Jensen",
    origin: "New Zealand / USA",
    age: 22,
    position: "Lock",
    tier: "Tier 1 Elite",
    rating: 92,
    squat: 530,
    bench: 385,
    fortyDash: "4.82",
    yardsPerCarry: "6.1",
    tackleCompletion: "93%",
    broncoTest: "4:42",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2026",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "cole-harrison",
    name: "Cole Harrison",
    origin: "USA",
    age: 21,
    position: "Lock",
    tier: "Tier 2",
    rating: 89,
    squat: 510,
    bench: 370,
    fortyDash: "4.88",
    yardsPerCarry: "5.8",
    tackleCompletion: "90%",
    broncoTest: "4:50",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2027",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "declan-walsh",
    name: "Declan Walsh",
    origin: "USA",
    age: 20,
    position: "Lock",
    tier: "Tier 2",
    rating: 87,
    squat: 500,
    bench: 360,
    fortyDash: "4.94",
    yardsPerCarry: "5.5",
    tackleCompletion: "89%",
    broncoTest: "4:56",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2028",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },

  // --- FLANKERS ---
  {
    id: "marcus-bradley",
    name: "Marcus Bradley",
    origin: "USA",
    age: 21,
    position: "Flanker",
    tier: "Tier 1 Elite",
    rating: 95,
    squat: 480,
    bench: 340,
    fortyDash: "4.64",
    yardsPerCarry: "6.9",
    tackleCompletion: "97%",
    broncoTest: "4:24",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2027",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "lucas-moreau",
    name: "Lucas Moreau",
    origin: "France / USA",
    age: 22,
    position: "Flanker",
    tier: "Tier 1 Elite",
    rating: 93,
    squat: 470,
    bench: 330,
    fortyDash: "4.67",
    yardsPerCarry: "6.7",
    tackleCompletion: "95%",
    broncoTest: "4:27",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2026",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "gavin-stewart",
    name: "Gavin Stewart",
    origin: "South Africa / USA",
    age: 20,
    position: "Flanker",
    tier: "Tier 2",
    rating: 90,
    squat: 450,
    bench: 320,
    fortyDash: "4.72",
    yardsPerCarry: "6.4",
    tackleCompletion: "92%",
    broncoTest: "4:34",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2027",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "owen-mercer",
    name: "Owen Mercer",
    origin: "USA",
    age: 21,
    position: "Flanker",
    tier: "Tier 2",
    rating: 88,
    squat: 440,
    bench: 310,
    fortyDash: "4.76",
    yardsPerCarry: "6.1",
    tackleCompletion: "91%",
    broncoTest: "4:40",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2028",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },

  // --- SCRUM-HALVES ---
  {
    id: "mateo-silva",
    name: "Mateo Silva",
    origin: "Argentina / USA",
    age: 21,
    position: "Scrum-Half",
    tier: "Tier 1 Elite",
    rating: 94,
    squat: 420,
    bench: 300,
    fortyDash: "4.52",
    yardsPerCarry: "7.8",
    tackleCompletion: "91%",
    broncoTest: "4:15",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2027",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "toby-lawrence",
    name: "Toby Lawrence",
    origin: "Australia / USA",
    age: 22,
    position: "Scrum-Half",
    tier: "Tier 1 Elite",
    rating: 92,
    squat: 410,
    bench: 290,
    fortyDash: "4.56",
    yardsPerCarry: "7.5",
    tackleCompletion: "89%",
    broncoTest: "4:19",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2026",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "ethan-bridge",
    name: "Ethan Bridge",
    origin: "USA",
    age: 20,
    position: "Scrum-Half",
    tier: "Tier 2",
    rating: 89,
    squat: 395,
    bench: 280,
    fortyDash: "4.61",
    yardsPerCarry: "7.2",
    tackleCompletion: "88%",
    broncoTest: "4:25",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2028",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "zach-miller",
    name: "Zach Miller",
    origin: "USA",
    age: 21,
    position: "Scrum-Half",
    tier: "Tier 2",
    rating: 87,
    squat: 385,
    bench: 270,
    fortyDash: "4.65",
    yardsPerCarry: "6.9",
    tackleCompletion: "86%",
    broncoTest: "4:30",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2027",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },

  // --- FLY-HALVES (WITH GOAL KICKING %) ---
  {
    id: "liam-oconnor",
    name: "Liam O'Connor",
    origin: "Ireland / USA",
    age: 20,
    position: "Fly-Half",
    tier: "Tier 1 Elite",
    rating: 96,
    squat: 400,
    bench: 290,
    fortyDash: "4.69",
    yardsPerCarry: "7.1",
    tackleCompletion: "89%",
    broncoTest: "4:18",
    goalKicking: "88.5%",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2027",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "julian-vargas",
    name: "Julian Vargas",
    origin: "Argentina",
    age: 21,
    position: "Fly-Half",
    tier: "Tier 1 Elite",
    rating: 94,
    squat: 390,
    bench: 280,
    fortyDash: "4.72",
    yardsPerCarry: "6.8",
    tackleCompletion: "87%",
    broncoTest: "4:21",
    goalKicking: "85.0%",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2026",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "charlie-daniels",
    name: "Charlie Daniels",
    origin: "USA",
    age: 22,
    position: "Fly-Half",
    tier: "Tier 2",
    rating: 90,
    squat: 380,
    bench: 270,
    fortyDash: "4.78",
    yardsPerCarry: "6.5",
    tackleCompletion: "85%",
    broncoTest: "4:28",
    goalKicking: "81.2%",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2027",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "finn-callahan",
    name: "Finn Callahan",
    origin: "USA",
    age: 20,
    position: "Fly-Half",
    tier: "Tier 2",
    rating: 88,
    squat: 370,
    bench: 260,
    fortyDash: "4.82",
    yardsPerCarry: "6.2",
    tackleCompletion: "84%",
    broncoTest: "4:35",
    goalKicking: "79.0%",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2028",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },

  // --- CENTERS ---
  {
    id: "darius-king",
    name: "Darius King",
    origin: "USA",
    age: 22,
    position: "Center",
    tier: "Tier 1 Elite",
    rating: 97,
    squat: 510,
    bench: 380,
    fortyDash: "4.58",
    yardsPerCarry: "8.4",
    tackleCompletion: "94%",
    broncoTest: "4:32",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2027",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "malik-johnson",
    name: "Malik Johnson",
    origin: "USA",
    age: 21,
    position: "Center",
    tier: "Tier 1 Elite",
    rating: 94,
    squat: 495,
    bench: 365,
    fortyDash: "4.61",
    yardsPerCarry: "8.1",
    tackleCompletion: "92%",
    broncoTest: "4:36",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2026",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "brendan-foster",
    name: "Brendan Foster",
    origin: "New Zealand / USA",
    age: 20,
    position: "Center",
    tier: "Tier 2",
    rating: 90,
    squat: 480,
    bench: 350,
    fortyDash: "4.66",
    yardsPerCarry: "7.6",
    tackleCompletion: "90%",
    broncoTest: "4:42",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2027",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "tyler-davis",
    name: "Tyler Davis",
    origin: "USA",
    age: 21,
    position: "Center",
    tier: "Tier 2",
    rating: 88,
    squat: 465,
    bench: 340,
    fortyDash: "4.70",
    yardsPerCarry: "7.3",
    tackleCompletion: "88%",
    broncoTest: "4:48",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2028",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },

  // --- WINGS ---
  {
    id: "ebenezer-adebayo",
    name: "Ebenezer Adebayo",
    origin: "UK / USA",
    age: 22,
    position: "Wing",
    tier: "Tier 1 Elite",
    rating: 98,
    squat: 460,
    bench: 330,
    fortyDash: "4.42",
    yardsPerCarry: "9.6",
    tackleCompletion: "88%",
    broncoTest: "4:20",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2026",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "kofi-mensah",
    name: "Kofi Mensah",
    origin: "Ghana / USA",
    age: 21,
    position: "Wing",
    tier: "Tier 1 Elite",
    rating: 95,
    squat: 450,
    bench: 320,
    fortyDash: "4.46",
    yardsPerCarry: "9.2",
    tackleCompletion: "86%",
    broncoTest: "4:23",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2027",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "hunter-brooks",
    name: "Hunter Brooks",
    origin: "USA",
    age: 20,
    position: "Wing",
    tier: "Tier 2",
    rating: 91,
    squat: 435,
    bench: 310,
    fortyDash: "4.51",
    yardsPerCarry: "8.7",
    tackleCompletion: "85%",
    broncoTest: "4:30",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2027",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "cameron-scott",
    name: "Cameron Scott",
    origin: "USA",
    age: 21,
    position: "Wing",
    tier: "Tier 2",
    rating: 89,
    squat: 420,
    bench: 300,
    fortyDash: "4.55",
    yardsPerCarry: "8.3",
    tackleCompletion: "83%",
    broncoTest: "4:35",
    recruitingStatus: "Active Uncommitted",
    classYear: "Class of 2028",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  }
];
